require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'doc/**/*'
    - 'node_modules/**/*'
    - 'spec/factories/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'

Style/Documentation:
  Enabled: false
