version: '3.3'
services:
  mysql:
    image: mysql:8.0.19
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/volumes:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    image: quicks
    command: /bin/sh -c 'rm -rf tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app/:cached
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: mysql
      RAILS_ENV: development
    depends_on:
      - mysql
    tty: true
    stdin_open: true
